Repository ec-europa/atomium, pull requests merged in 2019-03, with the labels that each got.

#217 Issue #215: Fix PHP 7.x compatibility.
  atomium/templates/table/table.component.inc
Labels: 7.x-2.x, Ready to review

#218 Issue #150 + #151: Optimize atomium_preprocess().
  atomium/includes/common.inc
  atomium/includes/preprocess.inc
Labels: 7.x-2.x

#239 Issue #237: Fix Drone builds failure probably related to drupal-composer/preserve-paths
  composer.json
Labels: 7.x-2.x, Ready to review

#238 Issue #232: Remove useless file.
  .php_cs.dist
Labels: 7.x-2.x

#226 NEPT-2271: Use a package (openeuropa/code-review or drupol/drupal-conventions) for code style checks.
  atomium/includes/alter/form.inc
  atomium/includes/classes/Attributes.php
  atomium/includes/classes/AttributesContainer.php
  atomium/includes/common.inc
  atomium/includes/process.inc
  atomium/includes/registry.inc
  atomium/templates/atomium_overview/atomium_overview.component.inc
  atomium/templates/block/block.component.inc
  atomium/templates/checkbox/checkbox.component.inc
  atomium/templates/comment/comment.component.inc
  atomium/templates/comment_wrapper/comment-wrapper.tpl.php
  atomium/templates/form_element/form-element.tpl.php
  atomium/templates/form_element/form_element.component.inc
  atomium/templates/form_element_label/form_element_label.component.inc
  atomium/templates/html/html.component.inc
  atomium/templates/html_tag/html_tag.component.inc
  atomium/templates/item_list/item_list.component.inc
  atomium/templates/link/link.component.inc
  atomium/templates/links/links.component.inc
  atomium/templates/mark/mark.component.inc
  atomium/templates/menu_local_task/menu_local_task.component.inc
  atomium/templates/node/node.component.inc
  atomium/templates/options_none/options_none.component.inc
  atomium/templates/page/page.component.inc
  atomium/templates/pager/pager.component.inc
  atomium/templates/radio/radio.component.inc
  atomium/templates/system_admin_index/system_admin_index.component.inc
  atomium/templates/table/table.component.inc
  atomium/templates/tablesort_indicator/tablesort_indicator.component.inc
  atomium/templates/user_picture/user_picture.component.inc
  atomium_bartik/templates/block/block.component.inc
  atomium_bartik/templates/html/html.component.inc
  atomium_bartik/templates/menu_local_tasks/menu_local_tasks.component.inc
  atomium_bartik/templates/node/node.component.inc
  atomium_bartik/templates/page/page.tpl.php
  atomium_bootstrap/includes/alter/form.inc
  atomium_bootstrap/templates/button/button.component.inc
  atomium_bootstrap/templates/fieldset/fieldset.process.inc
  atomium_bootstrap/templates/link/link.component.inc
  atomium_bootstrap/templates/links/links.component.inc
  atomium_bootstrap/templates/menu_local_task/menu_local_task.component.inc
  atomium_bootstrap/templates/pager/pager.component.inc
  atomium_bootstrap/templates/region/region.component.inc
  atomium_foundation/templates/button/button.component.inc
  atomium_foundation/templates/container/container.component.inc
  atomium_foundation/templates/form_element/form-element.tpl.php
  atomium_foundation/templates/link/link.component.inc
  atomium_foundation/templates/menu_local_task/menu_local_task.component.inc
  atomium_foundation/templates/menu_local_tasks/menu_local_tasks.component.inc
  atomium_foundation/templates/menu_tree/menu_tree.component.inc
  atomium_foundation/templates/region/region.component.inc
  composer.json
  grumphp.yml.dist
  tests/src/Kernel/AbstractKernelTest.php
  tests/src/Kernel/ThemeTest.php
  tests/src/Unit/AbstractUnitTest.php
  tests/src/Unit/AttributesContainerTest.php
  tests/src/Unit/AttributesTest.php
Labels: 7.x-2.x

#236 Issue #234: Update git ignore file.
  .gitignore
Labels: 7.x-2.x

#243 Issue #241: Synchronised runner yml file.
  runner.yml.dist
Labels: 7.x-2.x

#249 Issue #230: Fix notice error.
  atomium/includes/registry.inc
  atomium/templates/html/html.component.inc
Labels: 7.x-2.x

#248 Issue #247: Improve atomium_theme_registry_alter().
  atomium/includes/common.inc
  atomium/includes/registry.inc
  atomium/templates/atomium_overview/atomium_overview.component.inc
Labels: 7.x-3.x

#250 Issue #247: Improve atomium_theme_registry_alter()
  atomium/includes/common.inc
  atomium/includes/registry.inc
  atomium/templates/atomium_overview/atomium_overview.component.inc
Labels: 7.x-2.x

#253 Issue #251: Update custom grumphp configuration.
  grumphp.yml.dist
Labels: 7.x-3.x, Ready to review

#252 Issue #251: Update custom grumphp configuration.
  composer.json
  grumphp.yml.dist
Labels: 7.x-2.x, Ready to review

#255 Issue #254: Upgrade components
  atomium/template.php
  atomium/templates/admin_block/admin_block.component.inc
  atomium/templates/admin_block_content/admin_block_content.component.inc
  atomium/templates/atomium_overview/atomium_overview.component.inc
  atomium/templates/block/block.component.inc
  atomium/templates/checkbox/checkbox.component.inc
  atomium/templates/checkboxes/checkboxes.component.inc
  atomium/templates/container/container.component.inc
  atomium/templates/date/date.component.inc
  atomium/templates/feed_icon/feed_icon.component.inc
  atomium/templates/fieldset/fieldset.component.inc
  atomium/templates/file_icon/file_icon.component.inc
  atomium/templates/filter_tips/filter_tips.component.inc
  atomium/templates/filter_tips_more_info/filter_tips_more_info.component.inc
  atomium/templates/image_button/image_button.component.inc
  atomium/templates/indentation/indentation.component.inc
  atomium/templates/item_list/item_list.component.inc
  atomium/templates/mark/mark.component.inc
  atomium/templates/more_help_link/more_help_link.component.inc
  atomium/templates/more_link/more_link.component.inc
  atomium/templates/options_none/options_none.component.inc
  atomium/templates/pager/pager.component.inc
  atomium/templates/pager_ellipsis/pager_ellipsis.component.inc
  atomium/templates/password/password.component.inc
  atomium/templates/progress_bar/progress-bar.tpl.php
  atomium/templates/progress_bar/progress_bar.component.inc
  atomium/templates/radio/radio.component.inc
  atomium/templates/radios/radios.component.inc
  atomium/templates/select/select.component.inc
  atomium/templates/table/table.component.inc
  atomium/templates/tablesort_indicator/tablesort_indicator.component.inc
  atomium/templates/textarea/textarea.component.inc
  atomium/templates/textfield/textfield.component.inc
  atomium/templates/user_picture/user_picture.component.inc
  atomium/templates/user_profile/user_profile.component.inc
  composer.json
Labels: 7.x-3.x, Needs work

#256 Issue #254: Add more definitions for the atomium-overview page.
  atomium/templates/admin_block/admin_block.component.inc
  atomium/templates/admin_block_content/admin_block_content.component.inc
  atomium/templates/checkbox/checkbox.component.inc
  atomium/templates/checkboxes/checkboxes.component.inc
  atomium/templates/container/container.component.inc
  atomium/templates/date/date.component.inc
  atomium/templates/feed_icon/feed_icon.component.inc
  atomium/templates/fieldset/fieldset.component.inc
  atomium/templates/file_icon/file_icon.component.inc
  atomium/templates/filter_tips/filter_tips.component.inc
  atomium/templates/filter_tips_more_info/filter_tips_more_info.component.inc
  atomium/templates/image_button/image_button.component.inc
  atomium/templates/indentation/indentation.component.inc
  atomium/templates/mark/mark.component.inc
  atomium/templates/more_help_link/more_help_link.component.inc
  atomium/templates/more_link/more_link.component.inc
  atomium/templates/options_none/options_none.component.inc
  atomium/templates/pager_ellipsis/pager_ellipsis.component.inc
  atomium/templates/password/password.component.inc
  atomium/templates/progress_bar/progress-bar.tpl.php
  atomium/templates/progress_bar/progress_bar.component.inc
  atomium/templates/radio/radio.component.inc
  atomium/templates/radios/radios.component.inc
  atomium/templates/select/select.component.inc
  atomium/templates/table/table.component.inc
  atomium/templates/tablesort_indicator/tablesort_indicator.component.inc
  atomium/templates/textarea/textarea.component.inc
  atomium/templates/textfield/textfield.component.inc
  atomium/templates/user_picture/user_picture.component.inc
  atomium/templates/user_profile/user_profile.component.inc
Labels: 7.x-2.x, Ready to review

#260 Issue #259: Fix regression introduced in 7.x-2.14.
  atomium/includes/registry.inc
Labels: 7.x-2.x, Ready to review

#264 Issue #261: Add render tests.
  composer.json
  tests/src/Kernel/SubThemeTest.php
  tests/themes/atomium_test/atomium_test.info
  tests/themes/atomium_test/template.php
  tests/themes/atomium_test/templates/more_link/more-link.tpl.php
  tests/themes/atomium_test/templates/more_link/more_link.component.inc
  tests/themes/atomium_test_test/atomium_test_test.info
  tests/themes/atomium_test_test/template.php
  tests/themes/atomium_test_test/templates/more_link/more-link.tpl.php
  tests/themes/atomium_test_test/templates/more_link/more_link.component.inc
Labels: 7.x-2.x

#268 Issue #267: Fix CS and runner configuration
  runner.yml.dist
  tests/src/Kernel/SubThemeTest.php
Labels: 7.x-2.x, Needs backport, Ready to review

#266 Issue #261: Add render tests.
  composer.json
  runner.yml.dist
  tests/src/Kernel/SubThemeTest.php
  tests/themes/atomium_test/atomium_test.info
  tests/themes/atomium_test/template.php
  tests/themes/atomium_test/templates/more_link/more-link.tpl.php
  tests/themes/atomium_test/templates/more_link/more_link.component.inc
  tests/themes/atomium_test_test/atomium_test_test.info
  tests/themes/atomium_test_test/template.php
  tests/themes/atomium_test_test/templates/more_link/more-link.tpl.php
  tests/themes/atomium_test_test/templates/more_link/more_link.component.inc
Labels: 7.x-3.x, Ready to review

#270 Issue #269: Remove obsolete hooks
  atomium/includes/alter/css.inc
  atomium/includes/alter/entity.inc
  atomium/includes/alter/form.inc
  atomium/includes/alter/js.inc
  atomium/includes/config.inc
  atomium/includes/registry.inc
  atomium/template.php
  atomium/templates/link/link.component.inc
  atomium/templates/links/links.component.inc
  atomium/templates/mark/mark.component.inc
  atomium/templates/pager/pager.component.inc
  src/AttributesContainer.php
Labels: 7.x-3.x, Needs backport, Ready to review

#273 Issue #272: Refactor atomium_get_theme_info() and add tests.
  atomium/includes/common.inc
  composer.json
  tests/fixtures/Unit/atomium_get_theme_info.yml
  tests/src/Unit/CommonFunctionsTest.php
  tests/themes/atomium_test/atomium_test.info
  tests/themes/atomium_test_test/atomium_test_test.info
Labels: 7.x-3.x, Ready to review

#274 Issue #272: Refactor atomium_get_theme_info() and add tests.
  atomium/includes/common.inc
  composer.json
  tests/fixtures/Unit/atomium_get_theme_info.yml
  tests/src/Unit/CommonFunctionsTest.php
  tests/themes/atomium_test/atomium_test.info
  tests/themes/atomium_test_test/atomium_test_test.info
Labels: 7.x-2.x, Ready to review

#276 Issue #258: Remove unmaintained subthemes
  README.md
  atomium_bootstrap/assets/css/style.css
  atomium_bootstrap/atomium_bootstrap.info
  atomium_bootstrap/includes/alter/form.inc
  atomium_bootstrap/template.php
  atomium_bootstrap/templates/breadcrumb/breadcrumb.component.inc
  atomium_bootstrap/templates/button/button.component.inc
  atomium_bootstrap/templates/fieldset/fieldset.component.inc
  atomium_bootstrap/templates/fieldset/fieldset.css
  atomium_bootstrap/templates/fieldset/fieldset.process.inc
  atomium_bootstrap/templates/fieldset/fieldset.tpl.php
  atomium_bootstrap/templates/form_required_marker/form_required_marker.component.inc
  atomium_bootstrap/templates/html/html.component.inc
  atomium_bootstrap/templates/link/link.component.inc
  atomium_bootstrap/templates/links/links.component.inc
  atomium_bootstrap/templates/mark/mark.component.inc
  atomium_bootstrap/templates/menu_local_action/menu-local-action.tpl.php
  atomium_bootstrap/templates/menu_local_action/menu_local_action.component.inc
  atomium_bootstrap/templates/menu_local_task/menu_local_task.component.inc
  atomium_bootstrap/templates/menu_local_tasks/menu_local_tasks.component.inc
  atomium_bootstrap/templates/menu_tree/menu_tree.component.inc
  atomium_bootstrap/templates/page/page.component.inc
  atomium_bootstrap/templates/page/page.tpl.php
  atomium_bootstrap/templates/pager/pager.component.inc
  atomium_bootstrap/templates/region/region.component.inc
  atomium_bootstrap/templates/status_messages/status_messages.component.inc
  atomium_bootstrap/templates/table/table.component.inc
  atomium_foundation/assets/css/style.css
  atomium_foundation/assets/js/foundation.behavior.js
  atomium_foundation/atomium_foundation.info
  atomium_foundation/template.php
  atomium_foundation/templates/block/block.component.inc
  atomium_foundation/templates/breadcrumb/breadcrumb.component.inc
  atomium_foundation/templates/button/button.component.inc
  atomium_foundation/templates/container/container.component.inc
  atomium_foundation/templates/fieldset/fieldset.component.inc
  atomium_foundation/templates/file/file.component.inc
  atomium_foundation/templates/form_element/form-element.tpl.php
  atomium_foundation/templates/form_required_marker/form_required_marker.component.inc
  atomium_foundation/templates/html/html.component.inc
  atomium_foundation/templates/link/link.component.inc
  atomium_foundation/templates/links/links.component.inc
  atomium_foundation/templates/mark/mark.component.inc
  atomium_foundation/templates/mark/mark.tpl.php
  atomium_foundation/templates/menu_local_action/menu-local-action.tpl.php
  atomium_foundation/templates/menu_local_action/menu_local_action.component.inc
  atomium_foundation/templates/menu_local_task/menu-local-task.tpl.php
  atomium_foundation/templates/menu_local_task/menu_local_task.component.inc
  atomium_foundation/templates/menu_local_tasks/menu_local_tasks.component.inc
  atomium_foundation/templates/menu_tree/menu_tree.component.inc
  atomium_foundation/templates/page/page.component.inc
  atomium_foundation/templates/page/page.tpl.php
  atomium_foundation/templates/pager/pager.component.inc
  atomium_foundation/templates/region/region.component.inc
  atomium_foundation/templates/search_block_form/search-block-form.tpl.php
  atomium_foundation/templates/status_messages/status_messages.component.inc
  atomium_foundation/templates/table/table.component.inc
Labels: 7.x-2.x, Ready to review

#279 Issue #277: Add pager component definitions so it can be shown on atomium-overview page.
  atomium/templates/pager/pager.component.inc
Labels: 7.x-3.x, Ready to review

#278 Issue #277: Add pager component definitions so it can be shown on atomium-overview page.
  atomium/templates/pager/pager.component.inc
Labels: 7.x-2.x, Ready to review

#271 Issue #269: Remove obsolete hooks.
  atomium/includes/alter/block.inc
  atomium/includes/alter/css.inc
  atomium/includes/alter/element_info.inc
  atomium/includes/alter/entity.inc
  atomium/includes/alter/field.inc
  atomium/includes/alter/form.inc
  atomium/includes/alter/js.inc
  atomium/includes/alter/page.inc
  atomium/includes/common.inc
  atomium/includes/config.inc
  atomium/includes/process.inc
  atomium/includes/registry.inc
  atomium/templates/link/link.component.inc
  atomium/templates/links/links.component.inc
  atomium/templates/mark/mark.component.inc
  atomium/templates/pager/pager.component.inc
Labels: 7.x-2.x, Ready to review

#282 Issue #280: Update docker-compose configuration file.
  docker-compose.yml
Labels: 7.x-2.x, Ready to review, enhancement

#281 Issue #280: Update docker-compose configuration file.
  docker-compose.yml
Labels: 7.x-3.x, Ready to review, enhancement

#286 Issue #284: Update package versions.
  atomium/includes/registry.inc
  atomium/theme-settings.php
  atomium_bartik/templates/page/page.component.inc
  composer.json
Labels: 7.x-2.x, Needs backport, enhancement

#289 Issue #284: Update composer package versions 7.x 3.x
  atomium/theme-settings.php
  atomium_bartik/templates/page/page.component.inc
  composer.json
Labels: Ready to review

#285 Issue #283: Fix notice errors, regression introduced in #269.
  atomium/templates/pager/pager.component.inc
Labels: 7.x-2.x, Needs backport, Ready to review, bug

#287 NEPT-2355: Fix table component and the way colgroups are handled.
  atomium/templates/table/table.component.inc
  atomium/templates/table/table.tpl.php
Labels: Ready to review, bug

#295 NEPT-2355: Fix table component and the way colgroups are handled.
  atomium/templates/table/table.component.inc
  atomium/templates/table/table.tpl.php
Labels: Ready to review, bug

#293 Issue #292: Update Drone configuration.
  .drone.yml
Labels: Ready to review, enhancement

#294 Issue #292: Update Drone configuration.
  .drone.yml
Labels: Ready to review, enhancement

#288 Issue #275: Update readme file
  README.md
Labels: 7.x-3.x, Needs backport, Needs work, enhancement

#297 Issue #296: [regression] - Assign value to the global variables: pager_total and pager_page_array.
  atomium/templates/pager/pager.component.inc
Labels: Needs backport, bug

#298 Issue #296: Assign value to the pager_total and pager_page_array vars.
  atomium/templates/pager/pager.component.inc
Labels: Ready to review, bug

#301 Issue #299: Update item_list component.
  atomium/templates/item_list/item_list.component.inc
  atomium/templates/menu_local_task/menu_local_task.component.inc
Labels: enhancement

#300 Issue #299: Update item_list component.
  atomium/templates/item_list/item_list.component.inc
  atomium/templates/menu_local_task/menu_local_task.component.inc
Labels: Ready to review, enhancement

#307 Issue #305: Fix textarea component regression.
  atomium/templates/textarea/textarea.component.inc
Labels: Ready to review, bug

#306 Issue #305: Fix textarea component regression.
  atomium/templates/textarea/textarea.component.inc
Labels: Ready to review, bug

#303 Issue #302: Ensure that we do not render a wrapping UL tag.
  atomium/templates/atomium_overview/atomium_overview.component.inc
Labels: Ready to review, bug

#309 Issue #308: Prevent notice error.
  atomium/templates/node/node.component.inc
Labels: Ready to review, bug

#310 Issue #308: Prevent notice error.
  atomium/templates/node/node.component.inc
Labels: Ready to review, bug

#312 Issue #311: Make sure that using strict type checks works.
  atomium/templates/radio/radio.component.inc
Labels: Ready to review, bug

#313 Issue #311: Make sure that using strict type checks works.
  atomium/templates/radio/radio.component.inc
Labels: Ready to review, bug

#316 Issue #314: Use string casting instead of int.
  atomium/templates/radio/radio.component.inc
Labels: Ready to review, bug

#315 Issue #314: Use string casting instead of int.
  atomium/templates/radio/radio.component.inc
Labels: Ready to review, bug

#318 Issue #317: Fix definition form data types.
  atomium/templates/radios/radios.component.inc
Labels: Ready to review, bug

#319 Issue #317: Fix definition form data types.
  atomium/templates/radios/radios.component.inc
Labels: Ready to review, bug

#322 Issue #320: Ensure that component not using the item_list component a…
  atomium/templates/atomium_overview/atomium_overview.component.inc
Labels: Ready to review, enhancement

#325 Issue #323: Update password component, enable placeholder by default.
  atomium/templates/password/password.component.inc
Labels: Ready to review, enhancement

#324 Issue #323: Update password component, enable placeholder by default.
  atomium/templates/password/password.component.inc
Labels: Ready to review, enhancement
