Repository ec-europa/atomium, pull requests merged in 2019-04, with the labels that each got.

#329 Issue #328: Fix image_style component.
  atomium/templates/image_style/image_style.component.inc
Labels: Needs backport, Ready to review, bug

#327 Issue #326: Add image_formatter component.
  atomium/templates/image_formatter/image-formatter.tpl.php
  atomium/templates/image_formatter/image_formatter.component.inc
Labels: Needs backport, Ready to review, enhancement

#337 Issue #336: Use recursive element children in the hook page alter.
  atomium/includes/alter/block.inc
  atomium/includes/alter/page.inc
  atomium/includes/common.inc
  atomium/templates/block/block.component.inc
  atomium/templates/dashboard_region/dashboard-region.tpl.php
  atomium/templates/image_formatter/image_formatter.component.inc
Labels: enhancement

#335 Issue #334: Refactor form alter using recurse element_children() function.
  atomium/includes/alter/form.inc
Labels: Needs backport, Ready to review, enhancement

#339 Issue #338: Let the field component uses the item_list component to render fields.
  atomium/templates/field/field.component.inc
  atomium/templates/field/field.tpl.php
  atomium/templates/item_list/item-list--field.tpl.php
  atomium/templates/item_list/item_list.component.inc
  atomium_bartik/templates/node/node.tpl.php
Labels: Needs backport, enhancement, question

#340 Issue #338: Field component use item_list component.
  atomium/templates/field/field.component.inc
  atomium/templates/field/field.tpl.php
  atomium/templates/item_list/item-list--field.tpl.php
  atomium/templates/item_list/item_list.component.inc
  composer.json
Labels: Ready to review, enhancement

#345 Issue #344: Update components
  atomium/templates/dashboard_disabled_blocks/dashboard-disabled-blocks.tpl.php
  atomium/templates/dashboard_disabled_blocks/dashboard_disabled_blocks.component.inc
  atomium/templates/system_powered_by/system_powered_by.component.inc
Labels: bug, enhancement

#349 Issue #348: Prevent anchor name collisions when rendering the page /atomium-overview
  atomium/templates/atomium_overview/atomium-overview.tpl.php
Labels: bug

#350 Issue #348: Prevent anchor name collisions when rendering the page /atomium-overview
  atomium/templates/atomium_overview/atomium-overview.tpl.php
Labels: bug

#352 Issue #351: Update pager components enabling class attributes on links.
  atomium/includes/classes/Attributes.php
  atomium/includes/common.inc
  atomium/templates/pager_first/pager_first.component.inc
  atomium/templates/pager_last/pager_last.component.inc
  atomium/templates/pager_next/pager_next.component.inc
  atomium/templates/pager_previous/pager_previous.component.inc
Labels: Needs backport, Needs work, enhancement

#356 Issue #354: Fix pager component - Add missing #element properties
  atomium/templates/pager/pager.component.inc
Labels: Ready to review, bug

#355 Issue #354: Fix pager component - Add missing #element properties
  atomium/templates/pager/pager.component.inc
Labels: Ready to review, bug
