Repository ec-europa/atomium, pull requests merged in 2019-06, with the labels that each got.

#426 Issue #425: Update item_list component.
  atomium/templates/indentation/indentation.component.inc
  atomium/templates/item_list/item-list.tpl.php
  atomium/templates/item_list/item_list.component.inc
  atomium/templates/menu_local_tasks/menu-local-tasks.tpl.php
  atomium/templates/menu_local_tasks/menu_local_tasks.component.inc
  atomium_bartik/templates/item_list/item_list.component.inc
Labels: 7.x-2.x, Needs backport, Ready to review, enhancement

#428 Issue #427: Update links component.
  atomium/templates/links/links.component.inc
  atomium/templates/links/links.tpl.php
Labels: 7.x-2.x, Needs backport, Ready to review, enhancement

#424 Issue #423: Update breadcrumb component.
  atomium/templates/breadcrumb/breadcrumb.component.inc
  atomium/templates/breadcrumb/breadcrumb.tpl.php
  atomium_bartik/templates/breadcrumb/breadcrumb.component.inc
  atomium_bartik/templates/breadcrumb/breadcrumb.tpl.php
Labels: 7.x-2.x, Needs backport, Ready to review, enhancement

#430 Issue #429: Update link component - use strings instead of render arrays.
  atomium/templates/feed_icon/feed_icon.component.inc
  atomium/templates/link/link.component.inc
  atomium/templates/link/link.tpl.php
  atomium/templates/menu_local_task/menu_local_task.component.inc
Labels: 7.x-2.x, Needs backport, Ready to review, enhancement

#437 Issue #436: Fix status_messages component.
  atomium/templates/status_messages/status_messages.component.inc
Labels: 7.x-2.x

#433 Issue #432: Append pager number as a pager property on each pager item.
  atomium/templates/pager/pager.component.inc
  atomium/templates/pager_current/pager-current.tpl.php
  atomium/templates/pager_current/pager_current.component.inc
  atomium/templates/pager_first/pager_first.component.inc
  atomium/templates/pager_last/pager_last.component.inc
  atomium/templates/pager_next/pager_next.component.inc
  atomium/templates/pager_previous/pager_previous.component.inc
Labels: 7.x-2.x, Needs backport, Ready to review, enhancement

#438 Issue #431: Fix form_element_label display.
  atomium/templates/form_element/form_element.component.inc
  atomium/templates/form_element_label/form_element_label.component.inc
Labels: 7.x-2.x, Needs backport, Ready to review, bug

#440 Issue #439: Prevent warnings when there is no arguments provided.
  atomium/templates/pager/pager.component.inc
  atomium_bartik/templates/pager/pager.tpl.php
Labels: 7.x-3.x, Needs backport, Ready to review, bug

#441 Issue #439: Prevent warnings when there is no arguments provided. (#440)
  atomium/templates/pager/pager.component.inc
  atomium_bartik/templates/pager/pager.tpl.php
Labels: 7.x-2.x, Ready to review, bug
