Repository ec-europa/atomium, pull requests merged in 2019-05, with the labels that each got.

#365 Issue #364: Use newest drupol/drupal-conventions
  atomium_bartik/templates/block/block.tpl.php
  composer.json
Labels: enhancement

#367 Issue #366: Make sure that values coming from database is properly typed
  atomium/templates/menu_tree/menu_tree.component.inc
Labels: enhancement

#360 Issue #359: Use PHP Taskman
  .drone.yml
  README.md
  composer.json
  taskman.yml.dist
Labels: Needs backport, Ready to review, enhancement

#376 Issue #375: Fix form element handling
  atomium/includes/alter/form.inc
  atomium/templates/fieldset/fieldset.component.inc
  atomium/templates/form_element/form_element.component.inc
  atomium/templates/form_element_label/form_element_label.component.inc
  atomium/templates/pager/pager.component.inc
  tests/themes/atomium_test/atomium_test.info
  tests/themes/atomium_test_test/atomium_test_test.info
Labels: Needs backport, Ready to review, bug

#379 Issue #378: Fix status report component
  atomium/templates/status_report/status_report.component.inc
Labels: 7.x-3.x, Needs backport, bug

#380 Issue #378: Fix status report component 7.x 2.x
  atomium/templates/status_report/status_report.component.inc
Labels: 7.x-2.x, Needs backport, bug

#385 Issue #384: Fix str_replace() argument order.
  atomium/templates/form_element/form_element.component.inc
Labels: Needs backport, Ready to review, bug

#389 Issue #387: Update compose and readme file to use taskman github:changelog package.
  .gitignore
  README.md
  composer.json
  taskman.yml.dist
Labels: 7.x-2.x, enhancement

#388 Issue #387: Update compose and readme file to use taskman github:changelog package.
  .gitignore
  README.md
  composer.json
Labels: 7.x-3.x, Needs backport, Ready to review, enhancement

#392 Issue #391: Prevent warnings when some properties are not set.
  atomium/templates/form_element/form_element.component.inc
Labels: 7.x-2.x, Ready to review, bug

#393 Issue #391: Prevent warnings when some properties are not set.
  atomium/templates/form_element/form_element.component.inc
Labels: 7.x-3.x, Ready to review, bug

#370 Issue #369: Docker improvements
  .env.dist
  .gitignore
  README.md
  docker-compose.yml
Labels: 7.x-2.x, enhancement

#371 Issue #369: Docker improvements
  .env.dist
  .gitignore
  README.md
  docker-compose.yml
Labels: 7.x-3.x, enhancement

#395 Issue #394: Rename file .env.dist to .env
  .env
  README.md
Labels: 7.x-3.x

#400 Issue #399: Update the project's license filename.
  LICENSE.txt
Labels: 7.x-2.x, Needs backport, Ready to review

#404 Issue #403: Fix form_element and form_element_label (Regression)
  atomium/templates/form_element/form_element.component.inc
Labels: 7.x-2.x, bug

#406 Issue #405: There is no need to render() the '#children' key, it will always be a string.
  atomium/templates/button/button.tpl.php
  atomium/templates/fieldset/fieldset.tpl.php
  atomium/templates/form/form.tpl.php
  atomium/templates/html_tag/html-tag.tpl.php
  atomium/templates/vertical_tabs/vertical-tabs.tpl.php
Labels: 7.x-2.x, Ready to review, enhancement

#407 Issue #405: There is no need to render() the '#children' key, it will always be a string.
  atomium/templates/button/button.tpl.php
  atomium/templates/fieldset/fieldset.tpl.php
  atomium/templates/form/form.tpl.php
  atomium/templates/html_tag/html-tag.tpl.php
  atomium/templates/vertical_tabs/vertical-tabs.tpl.php
Labels: 7.x-3.x, Ready to review, enhancement

#410 Issue #408: Add missing h2 tag in vertical_tabs element/component.
  README.md
  atomium/templates/vertical_tabs/vertical-tabs.tpl.php
Labels: 7.x-3.x, Ready to review, enhancement

#409 Issue #408: Add missing h2 tag in vertical_tabs element/component.
  README.md
  atomium/templates/vertical_tabs/vertical-tabs.tpl.php
Labels: 7.x-2.x, Ready to review, enhancement

#412 Issue #411: Fix bug that occurs when the value of an attribute is equal to zero
  atomium/includes/classes/Attributes.php
Labels: 7.x-2.x, Ready to review, bug

#414 Issue #413: Minor components optimizations.
  atomium/templates/admin_page/admin_page.component.inc
  atomium/templates/container/container--form.tpl.php
  atomium/templates/container/container.component.inc
  atomium/templates/container/container.tpl.php
  atomium/templates/form_element/form-element.tpl.php
  atomium/templates/form_element/form_element.component.inc
  atomium/templates/menu_overview_form/menu_overview_form.component.inc
  atomium/templates/menu_tree/menu-tree.tpl.php
  atomium/templates/node_add_list/node-add-list.tpl.php
  atomium/templates/pager/pager.component.inc
Labels: 7.x-2.x, Needs backport, Ready to review, enhancement

#420 Issue #419: Update pager component and provide the type of pager item in a property
  atomium/templates/pager/pager.component.inc
Labels: 7.x-2.x, Needs backport, Ready to review, enhancement

#418 Issue #415: the #children key property must be set by Drupal, not by the user.
  atomium/templates/container/container.component.inc
Labels: 7.x-2.x, Needs backport, Ready to review, bug

#417 Issue #416: Update status_messages component.
  atomium/templates/status_messages/status_messages.component.inc
  atomium_bartik/templates/status_messages/status_messages.component.inc
Labels: 7.x-2.x, Needs backport, Ready to review, enhancement

#422 Issue #421: Update atomium_get_settings() behavior.
  atomium/includes/common.inc
Labels: 7.x-2.x, Needs backport, Ready to review, enhancement
